from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

import numpy as np

from .models import CameraConfig, PatternPreparationResult
from .waveform import WaveformPlan


@runtime_checkable
class CameraAdapter(Protocol):

    def initialize(self) -> None: ...

    def list_devices(self) -> list[dict[str, Any]]: ...

    def is_connected(self) -> bool: ...

    def connection_info(self) -> dict[str, Any]: ...

    def connect(self, device_index: int | None = None, device_label: str = "") -> dict[str, Any]: ...

    def disconnect(self) -> None: ...

    def apply_config(self, config: CameraConfig) -> dict[str, Any]: ...

    def get_supported_bit_depths(self) -> list[int]: ...

    @property
    def preview_active(self) -> bool: ...

    def start_preview(self, config: CameraConfig, frame_buffer_count: int = 3) -> None: ...

    def read_preview_frame(self, timeout_ms: int = 100) -> np.ndarray: ...

    def stop_preview(self) -> None: ...

    def arm(self, frame_count: int) -> None: ...

    def disarm(self) -> None: ...

    def read_frame_sequence(
        self,
        frame_count: int,
        pattern_files: list[str],
        laser_wavelength_nm: int,
        frame_callback: Any | None = None,
        stop_event: Any | None = None,
    ) -> tuple[np.ndarray, list[float]]: ...


@runtime_checkable
class SlmAdapter(Protocol):

    def initialize(self) -> None: ...

    def list_devices(self) -> list[dict[str, str]]: ...

    def is_connected(self) -> bool: ...

    def connection_info(self) -> dict[str, Any]: ...

    def connect(self, device_path: str | None = None) -> dict[str, Any]: ...

    def disconnect(self) -> None: ...

    def list_running_orders(self) -> list[tuple[int, str]]: ...

    def select_running_order(self, ro_index: int) -> dict[str, Any]: ...

    def program_patterns(self, pattern_files: list[str], device_path: str | None = None) -> PatternPreparationResult: ...

    def activate_prepared_patterns(self) -> None: ...

    def prepared_summary(self) -> dict[str, Any]: ...


@runtime_checkable
class DaqAdapter(Protocol):

    def list_devices(self, default_device: str = "Dev1") -> list[str]: ...

    def list_port0_lines(self, device_name: str | None = None, default_device: str | None = None) -> list[str]: ...

    def play_waveform(self, device_name: str, plan: WaveformPlan, stop_event: Any | None = None) -> None: ...

    def set_all_low(self, device_name: str) -> None: ...

    def pulse_line(self, device_name: str, line_index: int, duration_s: float) -> None: ...
